watch_folder: ~/Downloads
debounce_seconds: 2

categories:
  Images:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .svg
    - .webp
    - .heic
    - .heif
    - .ico
    - .bmp
    - .tiff
    - .tif
    - .raw
    - .cr2
    - .nef
    - .psd
    - .ai
    - .eps
    - .avif
    - .jfif

  Documents:
    - .pdf
    - .doc
    - .docx
    - .xls
    - .xlsx
    - .ppt
    - .pptx
    - .txt
    - .rtf
    - .odt
    - .ods
    - .odp
    - .csv
    - .pages
    - .numbers
    - .key
    - .md
    - .tex
    - .log

  Videos:
    - .mp4
    - .mov
    - .avi
    - .mkv
    - .webm
    - .flv
    - .wmv
    - .m4v
    - .mpg
    - .mpeg
    - .3gp
    - .ts
    - .vob

  Audio:
    - .mp3
    - .wav
    - .aac
    - .flac
    - .m4a
    - .ogg
    - .wma
    - .aiff
    - .alac
    - .opus
    - .mid
    - .midi

  Archives:
    - .zip
    - .rar
    - .7z
    - .tar
    - .gz
    - .bz2
    - .xz
    - .tgz
    - .tbz2
    - .lz
    - .lzma
    - .cab
    - .iso
    - .img

  Code:
    - .py
    - .js
    - .ts
    - .jsx
    - .tsx
    - .html
    - .htm
    - .css
    - .scss
    - .sass
    - .less
    - .json
    - .xml
    - .yaml
    - .yml
    - .toml
    - .ini
    - .cfg
    - .conf
    - .sh
    - .bash
    - .zsh
    - .bat
    - .ps1
    - .sql
    - .java
    - .c
    - .cpp
    - .h
    - .hpp
    - .cs
    - .go
    - .rs
    - .rb
    - .php
    - .swift
    - .kt
    - .scala
    - .r
    - .lua
    - .pl
    - .ex
    - .exs
    - .vue
    - .svelte
    - .astro
    - .ipynb

  Applications:
    - .dmg
    - .pkg
    - .app
    - .exe
    - .msi
    - .deb
    - .rpm
    - .appimage
    - .apk
    - .ipa

  Fonts:
    - .ttf
    - .otf
    - .woff
    - .woff2
    - .eot
    - .fon

  Ebooks:
    - .epub
    - .mobi
    - .azw
    - .azw3
    - .fb2
    - .djvu

  3D:
    - .obj
    - .fbx
    - .stl
    - .blend
    - .3ds
    - .dae
    - .gltf
    - .glb

  Design:
    - .fig
    - .sketch
    - .xd
    - .indd
    - .afdesign
    - .afphoto
